
import { UIStrings } from './types';
import { COUNTRIES } from './countries';

export { COUNTRIES };

export const STORE_SEARCH_PATTERNS: Record<string, string> = {
  // Saudi & Gulf Major Stores
  'amazon': 'https://www.amazon.sa/s?k={{QUERY}}',
  'noon': 'https://www.noon.com/saudi-en/search?q={{QUERY}}',
  'jarir': 'https://www.jarir.com/sa-en/search?q={{QUERY}}',
  'extra': 'https://www.extra.com/en-sa/search?q={{QUERY}}',
  'saco': 'https://www.saco.sa/en/search/?text={{QUERY}}',
  'virgin': 'https://www.virginmegastore.sa/en/search/?text={{QUERY}}',
  'nahdi': 'https://www.nahdionline.com/en/catalogsearch/result/?q={{QUERY}}',
  'nice': 'https://www.nice.com.sa/en/search?q={{QUERY}}',
  'west elm': 'https://www.westelm.com.sa/en/search/?q={{QUERY}}',
  'pottery barn': 'https://www.potterybarn.com.sa/en/search/?q={{QUERY}}',
  'ikea': 'https://www.ikea.com/sa/en/search/products/?q={{QUERY}}',
  
  // Jordan & Levant
  'opensooq': 'https://jo.opensooq.com/ar/find?term={{QUERY}}', 
  'dna': 'https://www.dna.jo/search?q={{QUERY}}&type=product',
  'leaders': 'https://leaders.jo/search?q={{QUERY}}',
  'smartbuy': 'https://smartbuy.jo/catalogsearch/result/?q={{QUERY}}',
  'city center': 'https://citycenter.jo/search?search={{QUERY}}',
  'ameed': 'https://ameed.jo/?s={{QUERY}}&post_type=product',
  'abdeen': 'https://abdeengrand.com/search?q={{QUERY}}',
  'bashiti': 'https://bashitistores.com/search?q={{QUERY}}',
  'hypermax': 'https://www.facebook.com/search/top?q=Hypermax%20Jordan%20{{QUERY}}',
  'miles': 'https://www.miles.com.jo/search?q={{QUERY}}',
  'carrefour': 'https://www.facebook.com/search/top?q=Hypermax%20Jordan%20{{QUERY}}',
  'ammancart': 'https://ammancart.com/search?q={{QUERY}}',
  'talabatey': 'https://talabatey.com/search?q={{QUERY}}',
  
  // Egypt
  'jumia': 'https://www.jumia.com.eg/catalog/?q={{QUERY}}',
  'b.tech': 'https://btech.com/en/catalogsearch/result/?q={{QUERY}}',
  '2b': 'https://2b.com.eg/en/catalogsearch/result/?q={{QUERY}}',
  
  // Global / General
  'ebay': 'https://www.ebay.com/sch/i.html?_nkw={{QUERY}}',
  'aliexpress': 'https://www.aliexpress.com/wholesale?SearchText={{QUERY}}',
  'shein': 'https://ar.shein.com/pdsearch/{{QUERY}}',
  'trendyol': 'https://www.trendyol.com/sr?q={{QUERY}}',
  'iherb': 'https://www.iherb.com/search?kw={{QUERY}}',
  'asos': 'https://www.asos.com/search/?q={{QUERY}}'
};

export const STRINGS: Record<'en' | 'ar', UIStrings> = {
  en: {
    title: "Nabih",
    slogan: "The Intelligence of Choice",
    subtitle: "Your AI-powered decision engine scanning the globe for the ultimate value.",
    placeholder: "Search for a product, service, or brand...",
    compareBtn: "Consult Nabih",
    bestValue: "Smart Choice",
    lowestPrice: "Best Deal",
    unitPrice: "Unit Price",
    reviews: "Reviews",
    rating: "Rating",
    features: "Key Specs",
    pros: "Highs",
    cons: "Lows",
    loading: "Scanning Markets, Social Media & Deal Sites...",
    loadingSub: "Comparing e-commerce, classifieds, and checking trending offers.",
    matchScoreHelp: "Nabih Score is based on price, quality, and community trust.",
    visitStore: "Visit Product", 
    loadMore: "Discover More",
    startSearch: "Get Started",
    startFreeTrial: "Sign Up Free",
    compareHeader: { main: "Shop", phrases: ["Smarter", "Better", "Right Now"] },
    historyTitle: "Insights Library",
    historySubtitle: "Your recent comparisons",
    auth: { 
      signIn: "Sign In", 
      signUp: "Create Account", 
      welcome: "Welcome Back",
      welcomeSubLogin: "Access your personalized insights",
      welcomeSubSignup: "Join the community of smart decision makers",
      name: "Identity Name",
      storeName: "Store Name",
      selectCountryPlaceholder: "Select Region",
      phone: "Connectivity",
      email: "Digital Address",
      password: "Security Key",
      switchSignup: "New here? Join us",
      switchLogin: "Existing member? Log in",
      pendingApproval: "Account Pending Approval",
      pendingDesc: "Your merchant account is currently under review. We will notify you via email once approved."
    },
    smartCriteria: { balanced: "Balanced", cheapest: "Budget", topQuality: "Premium", excellentCondition: "Excellent Cond." },
    shipping: "Logistics",
    shippingCost: "Shipping Cost",
    deliveryTime: "Delivery Time",
    warranty: "Protection",
    returnPolicy: "Return",
    availability: "Stock",
    inStock: "Ready",
    outStock: "Sold Out",
    nabihVerdict: "Nabih's Verdict",
    footerDesc: "Democratizing market intelligence through advanced AI analytics.",
    madeBy: "POWERED BY",
    nextGenBadge: "AI Market Guard",
    noHistory: "Your library is empty.",
    history: "Library",
    clearHistory: "Purge Records",
    globalSearch: "Global + Local",
    localSearchOnly: "Local Only",
    compareProducts: "Compare 2 Items",
    selectToCompare: "Add to Compare",
    comparing: "Comparing",
    clearSelection: "Clear",
    redirectingMsg: "Securing connection to retailer...",
    platforms: {
      consumer: "Consumer Platform",
      merchant: "Merchant Platform",
      switch: "Switch Platform"
    }
  },
  ar: {
    title: "نبيه",
    slogan: "هندسة الاختيار.. ذكاء القرار",
    subtitle: "محركك الذكي الذي يجوب فضاء الإنترنت بحثاً عن القيمة الحقيقية، بعيداً عن صخب الإعلانات.",
    placeholder: "عن ماذا تبحث اليوم؟ (جوال، عطر، خدمة...)",
    compareBtn: "استشر نبيه",
    bestValue: "خيار نبيه الذكي",
    lowestPrice: "الصفقة الأوفر",
    unitPrice: "سعر الوحدة",
    reviews: "تقييمات المستخدمين",
    rating: "الجودة",
    features: "المواصفات الجوهرية",
    pros: "نقاط القوة",
    cons: "نقاط الانتباه",
    loading: "جاري مسح المتاجر، مواقع العروض، والتواصل الاجتماعي...",
    loadingSub: "نقوم بمقارنة الأسعار العالمية والمحلية والبحث عن أكواد الخصم.",
    matchScoreHelp: "مقياس نبيه يعتمد على خوارزمية توازن بين السعر، الجودة، والموثوقية.",
    visitStore: "اذهب للمتجر",
    loadMore: "كشف المزيد من النتائج",
    startSearch: "ابدأ رحلة البحث",
    startFreeTrial: "انضم لنبيه مجاناً",
    compareHeader: { main: "تسوق", phrases: ["بذكاء", "بثقة", "بنباهة"] },
    historyTitle: "أرشيف القرارات",
    historySubtitle: "سجل عمليات البحث والمقارنات السابقة",
    auth: { 
      signIn: "تسجيل الدخول", 
      signUp: "إنشاء حساب جديد", 
      welcome: "مرحباً بعودتك",
      welcomeSubLogin: "سجل دخولك لمتابعة قراراتك الشرائية",
      welcomeSubSignup: "انضم لمجتمع المتسوقين الأذكياء",
      name: "الاسم الكريم",
      storeName: "اسم المتجر",
      selectCountryPlaceholder: "اختر دولتك",
      phone: "رقم الجوال",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      switchSignup: "ليس لديك حساب؟ انضم إلينا",
      switchLogin: "لديك حساب بالفعل؟ سجل دخولك",
      pendingApproval: "الحساب قيد المراجعة",
      pendingDesc: "حساب التاجر الخاص بك قيد المراجعة حالياً. سنقوم بإشعارك عبر البريد الإلكتروني عند الموافقة."
    },
    smartCriteria: { balanced: "الخيار المتوازن", cheapest: "الأقل سعراً", topQuality: "الأعلى جودة", excellentCondition: "الأفضل حالاً" },
    shipping: "الشحن والتوصيل",
    shippingCost: "تكلفة الشحن",
    deliveryTime: "وقت الوصول المتوقع",
    warranty: "الضمان والحماية",
    returnPolicy: "سياسة الإرجاع",
    availability: "حالة التوفر",
    inStock: "متوفر حالياً",
    outStock: "نفذت الكمية",
    nabihVerdict: "خلاصة نبيه",
    footerDesc: "نمكنك من اتخاذ قرارات شرائية صائبة باستخدام أدوات تحليل البيانات المتقدمة.",
    madeBy: "تم التطوير بواسطة",
    nextGenBadge: "مستشارك الرقمي",
    noHistory: "لا يوجد سجل بحث محفوظ حتى الآن.",
    history: "السجل",
    clearHistory: "حذف السجل",
    globalSearch: "بحث عالمي",
    localSearchOnly: "متاجر محلية",
    compareProducts: "مقارنة منتجين",
    selectToCompare: "إضافة للمقارنة",
    comparing: "جاري المقارنة",
    clearSelection: "إلغاء",
    redirectingMsg: "جاري تأمين الاتصال وتوجيهك للمتجر...",
    platforms: {
      consumer: "منصة الأفراد",
      merchant: "منصة التجار",
      switch: "تبديل المنصة"
    }
  }
};
