
export interface Country {
  id: string;
  en: string;
  ar: string;
  prefix: string;
}

export const COUNTRIES: Country[] = [
  { id: 'SA', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية', prefix: '+966' },
  { id: 'JO', en: 'Jordan', ar: 'الأردن', prefix: '+962' },
  { id: 'AE', en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة', prefix: '+971' },
  { id: 'EG', en: 'Egypt', ar: 'مصر', prefix: '+20' },
  { id: 'KW', en: 'Kuwait', ar: 'الكويت', prefix: '+965' },
  { id: 'QA', en: 'Qatar', ar: 'قطر', prefix: '+974' },
  { id: 'OM', en: 'Oman', ar: 'عمان', prefix: '+968' },
  { id: 'BH', en: 'Bahrain', ar: 'البحرين', prefix: '+973' },
  { id: 'IQ', en: 'Iraq', ar: 'العراق', prefix: '+964' },
  { id: 'LB', en: 'Lebanon', ar: 'لبنان', prefix: '+961' },
  { id: 'YE', en: 'Yemen', ar: 'اليمن', prefix: '+967' },
  { id: 'PS', en: 'Palestine', ar: 'فلسطين', prefix: '+970' },
  { id: 'SY', en: 'Syria', ar: 'سوريا', prefix: '+963' },
  { id: 'LY', en: 'Libya', ar: 'ليبيا', prefix: '+218' },
  { id: 'TN', en: 'Tunisia', ar: 'تونس', prefix: '+216' },
  { id: 'DZ', en: 'Algeria', ar: 'الجزائر', prefix: '+213' },
  { id: 'MA', en: 'Morocco', ar: 'المغرب', prefix: '+212' },
  { id: 'SD', en: 'Sudan', ar: 'السودان', prefix: '+249' },
  { id: 'TR', en: 'Turkey', ar: 'تركيا', prefix: '+90' },
  { id: 'US', en: 'United States', ar: 'الولايات المتحدة', prefix: '+1' },
  { id: 'UK', en: 'United Kingdom', ar: 'المملكة المتحدة', prefix: '+44' },
  { id: 'CA', en: 'Canada', ar: 'كندا', prefix: '+1' },
  { id: 'DE', en: 'Germany', ar: 'ألمانيا', prefix: '+49' },
  { id: 'FR', en: 'France', ar: 'فرنسا', prefix: '+33' },
  { id: 'IT', en: 'Italy', ar: 'إيطاليا', prefix: '+39' },
  { id: 'ES', en: 'Spain', ar: 'إسبانيا', prefix: '+34' },
  { id: 'CN', en: 'China', ar: 'الصين', prefix: '+86' },
  { id: 'JP', en: 'Japan', ar: 'اليابان', prefix: '+81' },
  { id: 'KR', en: 'South Korea', ar: 'كوريا الجنوبية', prefix: '+82' },
  { id: 'IN', en: 'India', ar: 'الهند', prefix: '+91' },
  { id: 'PK', en: 'Pakistan', ar: 'باكستان', prefix: '+92' },
  { id: 'BD', en: 'Bangladesh', ar: 'بنغلاديش', prefix: '+880' },
  { id: 'ID', en: 'Indonesia', ar: 'إندونيسيا', prefix: '+62' },
  { id: 'MY', en: 'Malaysia', ar: 'ماليزيا', prefix: '+60' },
  { id: 'AU', en: 'Australia', ar: 'أستراليا', prefix: '+61' },
  { id: 'NZ', en: 'New Zealand', ar: 'نيوزيلندا', prefix: '+64' },
  { id: 'RU', en: 'Russia', ar: 'روسيا', prefix: '+7' },
  { id: 'BR', en: 'Brazil', ar: 'البرازيل', prefix: '+55' },
  { id: 'MX', en: 'Mexico', ar: 'المكسيك', prefix: '+52' },
  { id: 'AR', en: 'Argentina', ar: 'الأرجنتين', prefix: '+54' },
  { id: 'ZA', en: 'South Africa', ar: 'جنوب أفريقيا', prefix: '+27' },
  { id: 'NG', en: 'Nigeria', ar: 'نيجيريا', prefix: '+234' },
  { id: 'SE', en: 'Sweden', ar: 'السويد', prefix: '+46' },
  { id: 'NO', en: 'Norway', ar: 'النرويج', prefix: '+47' },
  { id: 'DK', en: 'Denmark', ar: 'الدانمارك', prefix: '+45' },
  { id: 'NL', en: 'Netherlands', ar: 'هولندا', prefix: '+31' },
  { id: 'BE', en: 'Belgium', ar: 'بلجيكا', prefix: '+32' },
  { id: 'CH', en: 'Switzerland', ar: 'سويسرا', prefix: '+41' },
  { id: 'AT', en: 'Austria', ar: 'النمسا', prefix: '+43' },
  { id: 'PT', en: 'Portugal', ar: 'البرتغال', prefix: '+351' },
  { id: 'GR', en: 'Greece', ar: 'اليونان', prefix: '+30' },
  { id: 'TH', en: 'Thailand', ar: 'تايلاند', prefix: '+66' },
  { id: 'VN', en: 'Vietnam', ar: 'فيتنام', prefix: '+84' },
  { id: 'PH', en: 'Philippines', ar: 'الفلبين', prefix: '+63' },
  { id: 'SG', en: 'Singapore', ar: 'سنغافورة', prefix: '+65' }
].sort((a, b) => a.ar.localeCompare(b.ar));
